version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node 

    steps:
      - checkout

      - restore_cache:
          keys:
            - postwill-bundle-v2-{{ checksum "postwill.gemspec" }}

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      - save_cache:
          key: postwill-bundle-v2-{{ checksum "postwill.gemspec" }}
          paths:
            - vendor/bundle

      - run:
          name: Run Rspec
          command: bundle exec rspec 
